# Generated by Django 2.2.4 on 2019-11-11 10:40

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stackhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rents', to='stackhome.Apartment'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rents', to='stackhome.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fridge', 'Fridge'), ('Desk', 'Desk'), ('Balcony', 'Balcony'), ('Cabinet', 'Cabinet'), ('Attached bath', 'Attached bath')], max_length=41),
        ),
    ]
