# Generated by Django 2.2.4 on 2019-10-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackhome', '0002_rent_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
